PracticaWeb/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.views import login, logout
from rest_framework import routers
from forkilla import views

router = routers.DefaultRouter()
router.register(r'restaurants', views.RestaurantViewSet)
router.register(r'reviews', views.ReviewViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.

urlpatterns = [
    url(r'^forkilla/', include('forkilla.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'', include('forkilla.urls')),
    url(r'^accounts/login/$',  login, name='login'),
    url(r'^accounts/logout/$',  logout,  {'next_page': '/restaurants/'}, name='logout'),
    url(r'^api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

forkilla/urls.py
from django.conf.urls import url

from . import views

listOfAddresses = ["https://sd2019-forkillaf1.herokuapp.com"]

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^restaurants/(?P<city>.*)/(?P<category>.*)/$', views.restaurants, name='restaurants'),
    url(r'^restaurants/(?P<city>.*)/$', views.restaurants, name='restaurants'),
    url(r'^restaurants/$', views.restaurants, name='restaurants'),
    url(r'^reservation/$', views.reservation, name='reservation'),
    url(r'^reviews/$', views.reviews, name='reviews'),
    url(r'^restaurant/(?P<restaurant_number>.*)/$', views.details, name='restaurant'),
    url(r'^checkout/$', views.checkout, name='checkout'),
    url(r'^register/$', views.register, name='register'),
    url(r'^admin/forkilla/restaurant/add/$', views.addrestaurant, name='addrestaurant'),
    url(r'^reservations/$', views.reservationlist, name='reservations'),
    url(r'^comparator/$', views.comparator, {'ips': listOfAddresses}, name='comparator'),
]

forkilla/models.py
from django.db import models
from datetime import datetime
from django.core.validators import MinValueValidator
from django.contrib.auth.models import User

# Create your models here.
class Restaurant(models.Model):
    CATEGORIES = (
        ("Rice", "Rice"),
        ("Fusi", "Fusion"),
        ("BBQ", "Barbecue"),
        ("Chin", "Chinese"),
        ("Medi", "Mediterranean"),
        ("Crep", "Creperie"),
        ("Hind", "Hindu"),
        ("Japa", "Japanese"),
        ("Ital", "Italian"),
        ("Mexi", "Mexican"),
        ("Peru", "Peruvian"),
        ("Russ", "Russian"),
        ("Turk", "Turkish"),
        ("Basq", "Basque"),
        ("Vegy", "Vegetarian"),
        ("Afri", "African"),
        ("Egyp", "Egyptian"),
        ("Grek", "Greek")
    )
    _d_categories = dict(CATEGORIES)


    restaurant_number = models.CharField(max_length=8, unique=True)
    name = models.CharField(max_length=50)
    menu_description = models.TextField()
    price_average = models.DecimalField(max_digits=5, decimal_places=2)
    is_promot = models.BooleanField()
    rate = models.DecimalField(max_digits=3, decimal_places=1)
    address = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    country = models.CharField(max_length=50)
    featured_photo = models.ImageField()
    category = models.CharField(max_length=5, choices=CATEGORIES)
    restaurant_capacity = models.PositiveIntegerField(max_length=3)


    def get_human_category(self):
        return self._d_categories[self.category]


    def __str__(self):
        return ('[**Promoted**]' if self.is_promot else '') + "[" + self.category + "] " \
                                                                                    "[" + self.restaurant_number + "] " + self.name + " - " + self.menu_description + " (" + str(
            self.rate) + ")" \
                         ": " + str(self.price_average) + u" €"

class Reservation(models.Model):
    SLOTS = (
        ("morning_first", "12h00"),
        ("morning_second", "13h00"),
        ("morning_third", "14h00"),
        ("morning_fourth", "15h00"),
        ("evening_first", "20h00"),
        ("evening_second", "21h00"),
        ("evening_third", "22h00"),
    )
    _d_slots = dict(SLOTS)

    id = models.AutoField(primary_key=True)
    restaurant = models.ForeignKey(Restaurant)
    user = models.ForeignKey(User, editable = False, default = 00)
    day = models.DateField(default=datetime.now)
    time_slot = models.CharField(max_length=15, choices=SLOTS)
    num_people = models.PositiveIntegerField(default=1, validators=[MinValueValidator(1)])

    def get_human_slot(self):
        return self._d_slots[self.time_slot]

class Review(models.Model):
    RATING = (
        ("Very Bad", "1"),
        ("Bad", "2"),
        ("OK", "3"),
        ("Good", "4"),
        ("Very Good", "5"),
    )
    _d_rating = dict(RATING)

    id = models.AutoField(primary_key=True)
    restaurant = models.ForeignKey(Restaurant)
    user = models.ForeignKey(User, editable=False, default=00)
    rating = models.CharField(max_length=15, choices=RATING)
    comment = models.CharField(max_length=150)

    def get_human_rating(self):
        return self._d_rating[self.rating]

class ViewedRestaurants(models.Model):
    id_vr = models.AutoField(primary_key=True)
    restaurant = models.ManyToManyField(Restaurant, through='RestaurantInsertDate')


class RestaurantInsertDate(models.Model):
    viewedrestaurants = models.ForeignKey(ViewedRestaurants, on_delete=models.CASCADE)
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
    date_added = models.DateTimeField(auto_now_add=True)
    class Meta:
        ordering = ['-date_added']

forkilla/forms.py
from django import forms
from .models import Reservation
from .models import Review
from .models import Restaurant

class ReservationForm(forms.ModelForm):
    class Meta:
        model = Reservation
        fields = ["day", "time_slot", "num_people"]

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ["rating", "comment"]

class ComparatorForm(forms.ModelForm):
    class Meta:
        model = Restaurant
        fields = ["city", "price_average","category"]

forkilla/views.py
from django.shortcuts import render
from .models import Restaurant
from .models import Reservation
from .models import ViewedRestaurants
from .models import Review
from .models import RestaurantInsertDate
from .forms import ReservationForm
from .forms import ReviewForm , ComparatorForm
from datetime import datetime, timedelta
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.contrib.auth.models import User, Group
from rest_framework import viewsets
from .serializers import RestaurantSerializer, ReviewSerializer
from .permissions import IsAdminOrCommercial


def _check_session(request):
    if "viewedrestaurants" not in request.session:
        viewedrestaurants = ViewedRestaurants()
        viewedrestaurants.save()
        request.session["viewedrestaurants"] = viewedrestaurants.id_vr
    else:
        viewedrestaurants = ViewedRestaurants.objects.get(id_vr=request.session["viewedrestaurants"])
    return viewedrestaurants

def index(request):
    restaurants_by_city = Restaurant.objects.filter(is_promot="True")
    promoted = True
    viewedrestaurants = _check_session(request)
    context = {
        'restaurants': restaurants_by_city,
        'user_name': request.user.username,
        'promoted': promoted,
        'admin': request.user.is_superuser,
        'viewedrestaurants': viewedrestaurants,
        'logged': request.user.is_authenticated(),
    }
    return render(request, 'forkilla/restaurants.html', context)


def restaurants(request, city="", category = ""):
    if request.GET.get('search_box', None):
        city = request.GET.get('search_box', None)
        context = {
            'logged': request.user.is_authenticated(),
            'user_name': request.user.username,
            'city': city,
            'category' : category,
            'admin': request.user.is_superuser,
            'restaurants':  Restaurant.objects.filter(city__iexact=city).order_by("category"),
            'promoted': False,
            'viewedrestaurants': _check_session(request)
        }
        return render(request, 'forkilla/restaurants.html', context)
    promoted = False
    if city:
        restaurants_filtered = Restaurant.objects.filter(city__iexact=city).order_by("category")
        if category:
            restaurants_filtered = Restaurant.objects.filter(city__iexact=city).filter(category__iexact=category)
    else:
        restaurants_filtered = Restaurant.objects.filter().order_by("category")
        promoted = False
    viewedrestaurants = _check_session(request)
    context = {
        'city': city,
        'category' : category,
        'restaurants': restaurants_filtered,
        'promoted': promoted,
        'admin': request.user.is_superuser,
        'logged': request.user.is_authenticated(),
        'user_name': request.user.username,
        'viewedrestaurants': viewedrestaurants
    }
    return render(request, 'forkilla/restaurants.html', context)

def details(request,restaurant_number=""):
    try:
        viewedrestaurants = _check_session(request)
        restaurant = Restaurant.objects.get(restaurant_number=restaurant_number)
        lastviewed = RestaurantInsertDate(viewedrestaurants=viewedrestaurants, restaurant=restaurant)
        lastviewed.save()
        reviews = Review.objects.filter(restaurant=restaurant)
        context = {
            'logged': request.user.is_authenticated(),
            'user_name': request.user.username,
            'reviews': reviews,
            'city': restaurant.city,
            'category': restaurant.category,
            'admin': request.user.is_superuser,
            'restaurant': restaurant,
            'viewedrestaurants': viewedrestaurants
        }
        return render(request, 'forkilla/details.html', context)

    except Restaurant.DoesNotExist:
        raise Http404


def checkout(request):
    try:
        if request.session["result"]=="OK":
            result = True
            full = False
        elif request.session["result"]=="FULL":
            result = True
            full = True
        viewedrestaurants = _check_session(request)
        context = {
            'logged': request.user.is_authenticated(),
            'user_name': request.user.username,
            'viewedrestaurants': viewedrestaurants,
            'result': result,
            'admin': request.user.is_superuser,
            'full': full,
        }
        return render(request, 'forkilla/checkout.html', context)
    except UnboundLocalError:
        return HttpResponse("No pots reservar per a 0 persones.")

@login_required
def reservation(request):
    try:
        if request.method == "POST":
            form = ReservationForm(request.POST)
            if form.is_valid():
                resv = form.save(commit=False)
                restaurant_number = request.session["reserved_restaurant"]
                resv.restaurant = Restaurant.objects.get(restaurant_number=restaurant_number)
                resv.user = request.user
                total_resv = 0
                for reserva in Reservation.objects.filter(restaurant_id=restaurant_number).filter(day=resv.day).filter(time_slot=resv.time_slot):
                    total_resv = total_resv + reserva.num_people
                if total_resv + resv.num_people < resv.restaurant.restaurant_capacity:
                    resv.save()
                    request.session["reservation"] = resv.id
                    request.session["result"] = "OK"
                else:
                    request.session["result"] = "FULL"
            else:
                request.session["result"] = form.errors
            return HttpResponseRedirect(reverse('checkout'))

        elif request.method == "GET":
            restaurant_number = request.GET["reservation"]
            request.session["reserved_restaurant"] = restaurant_number

            form = ReservationForm()
            viewedrestaurants = _check_session(request)
            restaurant = Restaurant.objects.get(restaurant_number = restaurant_number)
            lastviewed = RestaurantInsertDate(viewedrestaurants=viewedrestaurants,restaurant = restaurant)
            lastviewed.save()
            context = {
                'logged': request.user.is_authenticated(),
                'user_name': request.user.username,
                'admin': request.user.is_superuser,
                'restaurant': restaurant,
                'form': form,
                'city': restaurant.city,
                'category': restaurant.category,
                'viewedrestaurants': viewedrestaurants
            }
    except Restaurant.DoesNotExist:
        raise Http404
    return render(request, 'forkilla/reservation.html', context)

@login_required
def reviews(request):
    try:
        if request.method == "POST":
            form = ReviewForm(request.POST)
            if form.is_valid():
                revw = form.save(commit=False)
                restaurant_number = request.session["reviewed_restaurant"]
                revw.restaurant = Restaurant.objects.get(restaurant_number=restaurant_number)
                revw.user = request.user
                revw.save()
                request.session["reviews"] = revw.id
                request.session["result"] = "OK"
            else:
                request.session["result"] = form.errors
            return HttpResponseRedirect(reverse('restaurants'))

        elif request.method == "GET":
            restaurant_number = request.GET["reviews"]
            request.session["reviewed_restaurant"] = restaurant_number

            form = ReviewForm()
            viewedrestaurants = _check_session(request)
            restaurant = Restaurant.objects.get(restaurant_number=restaurant_number)
            context = {
                'logged': request.user.is_authenticated(),
                'user_name': request.user.username,
                'restaurant': restaurant,
                'admin': request.user.is_superuser,
                'form': form,
                'city': restaurant.city,
                'category': restaurant.category,
                'viewedrestaurants': viewedrestaurants
            }
    except Restaurant.DoesNotExist:
        return HttpResponse("Restaurant Does not exists")
    return render(request, 'forkilla/reviews.html', context)

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            return HttpResponseRedirect(reverse("index"))
    else:
        form = UserCreationForm()
    return render(request, "registration/register.html", {
        'form': form,
    })

@login_required
def reservationlist(request):

    if request.method == 'POST':
        Reservation.objects.filter(id = request.POST["delete_reservation"]).delete()
    reservationsPastUser = Reservation.objects.filter(user = request.user).order_by("day").filter(day__range=("2010-01-01", datetime.now().date()-timedelta(1)))
    reservationsFutureUser = Reservation.objects.filter(user = request.user).order_by("day").filter(day__range=(datetime.now().date(), "2020-01-01" ))

    viewedrestaurants = _check_session(request)


    context = {
        'logged': request.user.is_authenticated(),
        'user_name': request.user.username,
        'reviews': reviews,
        'admin': request.user.is_superuser,
        'reservations_past': reservationsPastUser,
        'reservations_future': reservationsFutureUser,
        'viewedrestaurants': viewedrestaurants,

    }


templates/forkilla/base.html
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
    * {box-sizing: border-box;}

    body {
        margin: 0;
        font-family: Arial, Helvetica, sans-serif;
    }

    .topnav {
        overflow: hidden;
        background-color: #e9e9e9;
    }

    .topnav a {
         float: left;
         display: block;
         color: black;
         text-align: center;
         padding: 14px 16px;
         text-decoration: none;
         font-size: 17px;
    }

    .topnav b {
        float: left;
        display: block;
        color: black;
        text-align: center;
        padding: 14px 16px;
        text-decoration: none;
        font-size: 17px;
    }

    .topnav a:hover {
        background-color: #ddd;
        color: black;
    }

    .topnav a.active {
        background-color: #2196F3;
        color: white;
    }

    .topnav .search-container {
        float: right;
    }

    .topnav input[type=text] {
        padding: 6px;
        margin-top: 8px;
        font-size: 17px;
        border: none;
    }

    .topnav .search-container button {
        float: right;
        padding: 6px;
        margin-top: 8px;
        margin-right: 16px;
        background: #ddd;
        font-size: 17px;
        border: none;
        cursor: pointer;
    }

    .topnav .search-container button:hover {
        background: #ccc;
    }

    @media screen and (max-width: 600px) {
        .topnav .search-container {
            float: none;
        }
        .topnav a, .topnav input[type=text], .topnav .search-container button {
            float: none;
            display: block;
            text-align: left;
            width: 100%;
            margin: 0;
            padding: 14px;
        }
        .topnav input[type=text] {
            border: 1px solid #ccc;
        }
    }
</style>

<div class="topnav">
    <b>FORKILLA</b>
    {% if admin %}
        <a href="{%url 'addrestaurant' %}"> Add restaurant </a>
    {% endif %}
    {% if logged %}
        <a href="{%url 'logout' %}?next={{next_url}}"> Logout </a>
        <a href="{%url 'reservations' %}"> My reservations </a>
        <b>Logged as {{user_name}}</b>
    {% else %}
        <a href="{%url 'login' %}?next={{next_url}}"> Login </a>
        <a href="{%url 'register' %}"> Registration </a>
    {% endif %}
    <div class="search-container">

    <form action="{% url 'restaurants'%}" method="SET" style="margin: 0">
        <input  id="search_box" type="text" name="search_box"  placeholder="City search..." >
        <button id="search_submit" type="submit" >Search</button>
    </form>
    </div>
</div>
<nav>
    <a href="{% url 'restaurants'%}">forkilla</a>/
    {% if city %}
    <a href="{% url 'restaurants' city%}">{{city}}</a>/
        {% if category %}
            <a href="{% url 'restaurants' city category%}">{{category}}</a>/
            {% if restaurant %}
                <a href="{% url 'restaurant' restaurant.restaurant_number%}">{{restaurant.name}}</a>/
            {% endif %}
        {% endif %}
    {% endif %}
</nav>
{% block content %}
{% endblock content%}
<hr/>
Your last viewed Restaurants <br>
<form action="{% url 'reservation'%}" method="get">
    {% for restaurant in viewedrestaurants.restaurantinsertdate_set.all|slice:"5"%}
    <a href="{% url 'restaurant' restaurant.restaurant.restaurant_number%}"> 	{{restaurant.restaurant.name}} </a> ({{restaurant.restaurant.rate}}) : 	{{restaurant.restaurant.menu_description}}
    <button type="submit" name="reservation" value={{restaurant.restaurant.restaurant_number}}>Reservation</button>
    <br>
    {% endfor %}
</form>

templates/forkilla/checkout.html
{% extends 'forkilla/base.html' %}
{% block content %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body style="background-color: #9ebd7e; color: #06581c;">
<h2>Result reservation</h2>
{% if result %}
    {% if full %}
        <h3> The restaurant is full </h3>
    {% else %}
        <h3>The reservation has been completed successfully </h3>
    {% endif %}
{% else %}
    <h3>ERROR</h3>
{% endif %}
</body>
</html>
{% endblock %}


templates/forkilla/comparator.html
{% extends 'forkilla/base.html' %}

{% block content %}
<div class="container" style="margin-top: 15px; margin-bottom: 15px;">
    <h4> Search restaurants by city, category and maximum price</h4>

    <input type="text" id="category" placeholder="Category">
    <input type="text" id="city" placeholder="City">
    <input type="text" id="price" placeholder="Price">
    <button onclick="filter()">Search</button>

    <ul id="callList" style="margin-top: 15px; margin-bottom: 15px;">

    </ul>
</div>

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>

    <script>
        function filter() {

            var city = document.getElementById('city').value;
            var category = document.getElementById('category').value;
            var price = document.getElementById('price').value;

            var api_url = "api/restaurants/?";
            var api_params = [];

            if(city)
                api_params.push("city=" + city);
            if(category)
                api_params.push("category=" + category);
            if(price)
                api_params.push("price=" + price);

            api_url += api_params.join("&");

            $.when(
                {% for ip in ips %}
                    $.ajax({
                        url: "https://" + "{{ip}}" + "/" + api_url
                    }),
                {% endfor %}
            ).then(function(
                {% for i in length %}
                    v{{i}},
                {% endfor %}
            )
            {
                var args = [].slice.apply(arguments);

                var a = [];
                {% for ip in ips %}
                    a.push("{{ip}}");
                {% endfor %}

                var calls = a.map(function (e, i) {
                    return [args[i], e];
                });

                var restaurants = []
                calls.forEach(function (call) {
                    var response = call[0];
                    var ip = call[1];
                    if(calls.length == 1){
                        response.results.forEach(function (restaurant) {
                            restaurants.push([restaurant, ip]);
                        });
                    }
                    else{
                        response[0].results.forEach(function (restaurant) {
                                restaurants.push([restaurant, ip]);
                            });
                    }
                });

                var $ul = $('#callList');
                $ul.empty();
                restaurants.sort(function (a, b) {
                    return a[0]["price_average"] - b[0]["price_average"]
                });
                var textnode = '<h5>Results from your search</h5>' + '<ul>';
                restaurants.forEach(function (obj) {
                    var restaurant = obj[0];
                    var ip = obj[1];
                    textnode +=
                        '<li>' +
                        '<h6>' + '<a href="https://' + ip + '/forkilla/restaurant/' + restaurant.restaurant_number + '/">' + restaurant.name + '</a>' + ', ' + restaurant.city + '</h6>' +
                        '<p>' + '<strong>' + 'Menu description: ' + '</strong>' + restaurant.menu_description + '<br>' +
                        '<strong>' + 'Price average: ' + '</strong>' + restaurant.price_average + '€. ' + '<br>' +
                        '<strong>' + 'Rating: ' + '</strong>' + restaurant.rate + ' out of 10. ' + '<br>' +
                        '<strong>' + 'Address: ' + '</strong>' + restaurant.address + '.' + '<br>' +
                        '<strong>' + 'From API: ' + '</strong>' + ip  + '</p>' +
                        '</li>';

                });
                textnode += '</ul>'
                $ul.append(textnode);
            }, error);

        }

        function error(e){
            console.log("Error: " + e.description);
        }
    </script>

{% endblock %}

templates/forkilla/details.html
{% extends 'forkilla/base.html' %}
{% block content %}
<html>
    <head>
        <meta charset="UTF-8" >
        <meta name="description" content="This the page that showns the details for a Forkilla's restaurant" >
        <title>{{restaurant.name}} details</title>
    </head>

    <body style="background-color: #9ebd7e; color: #06581c;">
        <header>
            <hr/>
            <h2>Restaurant details.</h2>
        </header>
        <main>
            <article> <!-- Specifications of the restaurant -->
                {% if restaurant %}

                    <div>
                    <dl>
                        <dt><h3>Restaurant: {{restaurant.name}}</h3></dt>
                        <dd><b>Menu description:</b> {{restaurant.menu_description}}</dd>
                        <dd><b>Average price:</b> {{restaurant.price_average}}</dd>
                        <dd><b>Promoted:</b> {{restaurant.is_promot}}</dd>
                        <dd><b>Rate:</b> {{restaurant.rate}}/10</dd>
                        <dd><b>Category:</b> {{restaurant.category}}</dd>
                        <dd><b>City:</b> {{restaurant.city}}</dd>
                        <dd><b>Adress:</b> {{restaurant.address}}</dd>
                        <dd><b>Country:</b> {{restaurant.country}}</dd>

                        <br/>
                        <form action="{% url 'reservation'%}" method="get">
                            <button type="submit" name="reservation" value={{restaurant.restaurant_number}}> Reservation </button>
                        </form>
                        <form action="{% url 'reviews'%}" method="get">
                            <button type="submit" name="reviews" value={{restaurant.restaurant_number}}> Add Review </button>
                        </form>
                    </dl>

                    </div>
                    <div style="position:absolute;top:170px; left:400px;">
                        {% if restaurant.featured_photo %}
                        {% load static %}
                        <img witdth="200" height="200" style="box-shadow: 5px 5px 5px green ; border-radius: 20%;" src="{% static restaurant.featured_photo %}" alt="My image"/>
                        {% else %}
                        <p>No image available.</p>
                        {% endif %}
                    </div>
                    <h3>REVIEWS</h3>
                    {% for review in reviews %}
                        <h4> <b>{{review.user.username}}: {{review.rating}}</b> </h4>
                        <li>
                            {{review.comment}}
                        </li>
                        <hr/>
                    {% endfor %}
                {% else %}
                    <p>No restaurants are available.</p>
                {% endif %}
            </article>
        </main>
        <footer>

        </footer>
    </body>
</html>
{% endblock%}

templates/forkilla/reservation.html
{% extends 'forkilla/base.html' %}
{% block content %}
<html>
    <head>
        <meta charset="UTF-8" >
        <meta name="description" content="This the page that showns the details for a Forkilla's restaurant" >
        <title> Forkilla </title>
    </head>
    <body s style="background-color: #9ebd7e; color: #06581c;">
        <header>
            <nav>
            </nav>
            <h2> Reviewing restaurant {{restaurant.name}}</h2>
        </header>

        <main>
            <form method="POST" >
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Save</button>
            </form>
        </main>
        <footer>

        </footer>
    </body>
</html>
{% endblock %}

templates/forkilla/reservationlist.html
{% extends 'forkilla/base.html' %}
{% block content %}
<html>
    <head>
        <meta charset="UTF-8" >
        <meta name="description" content="This the page that showns the details for a Forkilla's restaurant" >
        <title> Forkilla </title>
    </head>
    <body s style="background-color: #9ebd7e; color: #06581c;">
        <header>
            <nav>
            </nav>
            <h2> Managing reservations</h2>
        </header>

        <main>
            {% for reservation in reservations_past %}
                <dl>
                    <dt><h3>Restaurant: {{reservation.restaurant.name}}</h3></dt>
                    <dd><b>Reservation day:</b> {{reservation.day}}</dd>
                    <dd><b>Time slot:</b> {{reservation.time_slot}}</dd>
                    <dd><b>Num people:</b> {{reservation.num_people}}</dd>
                    <form action="{% url 'reviews'%}" method="get">
                        <button type="submit" name="reviews" value={{reservation.restaurant.restaurant_number}}> Add Review </button>
                    </form>
                </dl>
            {% endfor %}
            {% for reservation in reservations_future %}
            <dl>
                <dt><h3>Restaurant: {{reservation.restaurant.name}}</h3></dt>
                <dd><b>Reservation day:</b> {{reservation.day}}</dd>
                <dd><b>Time slot:</b> {{reservation.time_slot}}</dd>
                <dd><b>Num people:</b> {{reservation.num_people}}</dd>
                <form action="{% url 'reservations'%}" method="post">
                    {% csrf_token %}
                    <button type="submit" name="delete_reservation" value={{reservation.id}}> Delete reservation </button>
                </form>

            </dl>
            {% endfor %}
        </main>
        <footer>

        </footer>
    </body>
</html>
{% endblock %}

templates/forkilla/reviews.html
{% extends 'forkilla/base.html' %}
{% block content %}
    <html>
    <head>
        <meta charset="UTF-8" >
        <meta name="description" content="This the page that showns the details for a Forkilla's restaurant" >
        <title> Forkilla </title>
    </head>
    <body s style="background-color: #9ebd7e; color: #06581c;">
    <header>
        <nav>

        </nav>
        <h2> Writing a review for the restaurant {{restaurant.name}}</h2>
    </header>

    <main>
        <form method="POST" >
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Save</button>
        </form>
    </main>
    <footer>

    </footer>
    </body>
    </html>
{% endblock %}